### ISSUE TITLE
Issue with Interpolations on JuliaBox

### ISSUE THREAD

**Issue by rafaeljjd** [tlycken/Interpolations.jl#29]
Hello, 
First of all, thank you for writing the package "Interpolations". I'm currently working on JuliaBox (at my workplace it is very difficult to install new programs!!). However, I'm having trouble loading the package.
When I try to add the package (julia>Pkg.clone("https://github.com/tlycken/Interpolations.jl.git") 
​I get the following:
​
INFO: Cloning Interpolations from https://github.com/tlycken/Interpolations.jl.git
Interpolations already exists
while loading In[12], in expression starting on line 1
 in error at error.jl:21
 in clone at pkg/entry.jl:148
 in clone at pkg/entry.jl:175
 in anonymous at ./pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#228__ at ./pkg/dir.jl:28
 in clone at pkg.jl:30

And when I try to use the package (julia> using Interpolations)
I get the following:

syntax: extra token "getindex" after end of expression
while loading /home/juser/.julia/v0.3/Interpolations/src/Interpolations.jl, in expression starting on line 170
while loading In[11], in expression starting on line 1
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52

**Comment by tlycken** [comment]
Your first error indicates that there already is a folder Interpolations in your .julia dir. What happens if you delete that and try again? 

Secondly we recently merged changes that require Julia 0.4, and you seem to be running 0.3. I'm not entirely sure how Pkg.clone() handles that, but it's not impossible that the last commit before the 0.4 requirement was introduced had the package in an unusable state. In any case, you won't be able to use the latest version, unfortunately.

**Comment by rafaeljjd** [comment]
Thank you!
